# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rag_service_pb2 as rag__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RAGAgentServiceStub(object):
    """Service definition for RAG Agent
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStockSummary = channel.unary_unary(
                '/rag.agent.RAGAgentService/GetStockSummary',
                request_serializer=rag__service__pb2.StockSummaryRequest.SerializeToString,
                response_deserializer=rag__service__pb2.StockSummaryResponse.FromString,
                _registered_method=True)
        self.ExplainVolatility = channel.unary_unary(
                '/rag.agent.RAGAgentService/ExplainVolatility',
                request_serializer=rag__service__pb2.VolatilityRequest.SerializeToString,
                response_deserializer=rag__service__pb2.VolatilityResponse.FromString,
                _registered_method=True)
        self.CompareSentiment = channel.unary_unary(
                '/rag.agent.RAGAgentService/CompareSentiment',
                request_serializer=rag__service__pb2.SentimentCompareRequest.SerializeToString,
                response_deserializer=rag__service__pb2.SentimentCompareResponse.FromString,
                _registered_method=True)
        self.RecommendPair = channel.unary_unary(
                '/rag.agent.RAGAgentService/RecommendPair',
                request_serializer=rag__service__pb2.PairRecommendationRequest.SerializeToString,
                response_deserializer=rag__service__pb2.PairRecommendationResponse.FromString,
                _registered_method=True)
        self.QueryRAG = channel.unary_unary(
                '/rag.agent.RAGAgentService/QueryRAG',
                request_serializer=rag__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=rag__service__pb2.QueryResponse.FromString,
                _registered_method=True)


class RAGAgentServiceServicer(object):
    """Service definition for RAG Agent
    """

    def GetStockSummary(self, request, context):
        """Get stock summary with context
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainVolatility(self, request, context):
        """Explain volatility spike
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareSentiment(self, request, context):
        """Compare sentiment between two tickers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecommendPair(self, request, context):
        """Recommend long/short pair
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryRAG(self, request, context):
        """General query with RAG
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStockSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockSummary,
                    request_deserializer=rag__service__pb2.StockSummaryRequest.FromString,
                    response_serializer=rag__service__pb2.StockSummaryResponse.SerializeToString,
            ),
            'ExplainVolatility': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainVolatility,
                    request_deserializer=rag__service__pb2.VolatilityRequest.FromString,
                    response_serializer=rag__service__pb2.VolatilityResponse.SerializeToString,
            ),
            'CompareSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareSentiment,
                    request_deserializer=rag__service__pb2.SentimentCompareRequest.FromString,
                    response_serializer=rag__service__pb2.SentimentCompareResponse.SerializeToString,
            ),
            'RecommendPair': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendPair,
                    request_deserializer=rag__service__pb2.PairRecommendationRequest.FromString,
                    response_serializer=rag__service__pb2.PairRecommendationResponse.SerializeToString,
            ),
            'QueryRAG': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryRAG,
                    request_deserializer=rag__service__pb2.QueryRequest.FromString,
                    response_serializer=rag__service__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.agent.RAGAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.agent.RAGAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGAgentService(object):
    """Service definition for RAG Agent
    """

    @staticmethod
    def GetStockSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.agent.RAGAgentService/GetStockSummary',
            rag__service__pb2.StockSummaryRequest.SerializeToString,
            rag__service__pb2.StockSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainVolatility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.agent.RAGAgentService/ExplainVolatility',
            rag__service__pb2.VolatilityRequest.SerializeToString,
            rag__service__pb2.VolatilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.agent.RAGAgentService/CompareSentiment',
            rag__service__pb2.SentimentCompareRequest.SerializeToString,
            rag__service__pb2.SentimentCompareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecommendPair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.agent.RAGAgentService/RecommendPair',
            rag__service__pb2.PairRecommendationRequest.SerializeToString,
            rag__service__pb2.PairRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryRAG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.agent.RAGAgentService/QueryRAG',
            rag__service__pb2.QueryRequest.SerializeToString,
            rag__service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
